CREATE TABLE IF NOT EXISTS public.contacts (like raw.contacts);
ALTER TABLE public.contacts DROP CONSTRAINT IF EXISTS code_pk;
ALTER TABLE public.contacts ADD CONSTRAINT code_pk PRIMARY KEY (code);

COMMENT ON COLUMN public.contacts.code IS 'Unique government unit ID';

LOCK TABLE public.contacts IN EXCLUSIVE MODE;

INSERT INTO public.contacts
    SELECT
        county,
        unitname,
        description,
        code,
        address,
        city,
        state,
        zip,
        firstname,
        lastname,
        title,
        phone,
        ext,
        fax,
        email_gov,
        ceofname,
        ceolname,
        ceotitle,
        ceoaddr,
        ceocity,
        ceostate,
        ceozip,
        ceophone,
        ceoext,
        ceofax,
        ceoemail,
        cfofname,
        cfolname,
        cfotitle,
        cfoaddr,
        cfocity,
        cfostate,
        cfozip,
        cfophone,
        cfoext,
        cfofax,
        cfoemail,
        pafname,
        palname,
        patitle,
        paaddr,
        pacity,
        pastate,
        pazip,
        paphone,
        paext,
        pafax,
        paemail,
        tiffname,
        tiflname,
        tiftitle,
        tifaddr,
        tifcity,
        tifstate,
        tifzip,
        tifphone,
        tifext,
        tiffax,
        tifemail,
        foiafname,
        foialname,
        foiatitle,
        foiaaddr,
        foiacity,
        foiastate,
        foiazip,
        foiaphone,
        foiaext,
        foiafax,
        foiaemail
    FROM raw.contacts
ON CONFLICT (code)
    DO UPDATE SET
        county = excluded.county,
        unitname = excluded.unitname,
        description = excluded.description,
        code = excluded.code,
        address = excluded.address,
        city = excluded.city,
        state = excluded.state,
        zip = excluded.zip,
        firstname = excluded.firstname,
        lastname = excluded.lastname,
        title = excluded.title,
        phone = excluded.phone,
        ext = excluded.ext,
        fax = excluded.fax,
        email_gov = excluded.email_gov,
        ceofname = excluded.ceofname,
        ceolname = excluded.ceolname,
        ceotitle = excluded.ceotitle,
        ceoaddr = excluded.ceoaddr,
        ceocity = excluded.ceocity,
        ceostate = excluded.ceostate,
        ceozip = excluded.ceozip,
        ceophone = excluded.ceophone,
        ceoext = excluded.ceoext,
        ceofax = excluded.ceofax,
        ceoemail = excluded.ceoemail,
        cfofname = excluded.cfofname,
        cfolname = excluded.cfolname,
        cfotitle = excluded.cfotitle,
        cfoaddr = excluded.cfoaddr,
        cfocity = excluded.cfocity,
        cfostate = excluded.cfostate,
        cfozip = excluded.cfozip,
        cfophone = excluded.cfophone,
        cfoext = excluded.cfoext,
        cfofax = excluded.cfofax,
        cfoemail = excluded.cfoemail,
        pafname = excluded.pafname,
        palname = excluded.palname,
        patitle = excluded.patitle,
        paaddr = excluded.paaddr,
        pacity = excluded.pacity,
        pastate = excluded.pastate,
        pazip = excluded.pazip,
        paphone = excluded.paphone,
        paext = excluded.paext,
        pafax = excluded.pafax,
        paemail = excluded.paemail,
        tiffname = excluded.tiffname,
        tiflname = excluded.tiflname,
        tiftitle  = excluded.tiftitle,
        tifaddr = excluded.tifaddr,
        tifcity = excluded.tifcity,
        tifstate = excluded.tifstate,
        tifzip = excluded.tifzip,
        tifphone = excluded.tifphone,
        tifext = excluded.tifext,
        tiffax = excluded.tiffax,
        tifemail = excluded.tifemail,
        foiafname = excluded.foiafname,
        foialname = excluded.foialname,
        foiatitle = excluded.foiatitle,
        foiaaddr = excluded.foiaaddr,
        foiacity = excluded.foiacity,
        foiastate = excluded.foiastate,
        foiazip = excluded.foiazip,
        foiaphone = excluded.foiaphone,
        foiaext = excluded.foiaext,
        foiafax = excluded.foiafax,
        foiaemail = excluded.foiaemail
;