CREATE TABLE IF NOT EXISTS public.contacts (
    county character varying,
    unitname character varying,
    description character varying,
    code character varying,
    address character varying,
    city character varying,
    state character varying,
    zip character varying,
    firstname character varying,
    lastname character varying,
    title character varying,
    phone character varying,
    ext character varying,
    fax character varying,
    email_gov character varying,
    ceofname character varying,
    ceolname character varying,
    ceotitle character varying,
    ceoaddr character varying,
    ceocity character varying,
    ceostate character varying,
    ceozip character varying,
    ceophone character varying,
    ceoext character varying,
    ceofax character varying,
    ceoemail character varying,
    cfofname character varying,
    cfolname character varying,
    cfotitle character varying,
    cfoaddr character varying,
    cfocity character varying,
    cfostate character varying,
    cfozip character varying,
    cfophone character varying,
    cfoext character varying,
    cfofax character varying,
    cfoemail character varying,
    pafname character varying,
    palname character varying,
    patitle character varying,
    paaddr character varying,
    pacity character varying,
    pastate character varying,
    pazip character varying,
    paphone character varying,
    paext character varying,
    pafax character varying,
    paemail character varying,
    tiffname character varying,
    tiflname character varying,
    tiftitle character varying,
    tifaddr character varying,
    tifcity character varying,
    tifstate character varying,
    tifzip character varying,
    tifphone character varying,
    tifext character varying,
    tiffax character varying,
    tifemail character varying,
    foiafname character varying,
    foialname character varying,
    foiatitle character varying,
    foiaaddr character varying,
    foiacity character varying,
    foiastate character varying,
    foiazip character varying,
    foiaphone character varying,
    foiaext character varying,
    foiafax character varying,
    foiaemail character varying,
    slug character varying
);

ALTER TABLE public.contacts DROP CONSTRAINT IF EXISTS code_pk;
ALTER TABLE public.contacts ADD CONSTRAINT code_pk PRIMARY KEY (code);

COMMENT ON COLUMN public.contacts.code IS 'Unique government unit ID';

LOCK TABLE public.contacts IN EXCLUSIVE MODE;

INSERT INTO public.contacts
    SELECT
        county,
        unitname,
        description,
        code,
        initcap(address),
        initcap(city),
        state,
        zip,
        initcap(firstname),
        initcap(lastname),
        initcap(title),
        regexp_replace(phone, '[^0-9]', '', 'g'),
        ext,
        regexp_replace(fax, '[^0-9]', '', 'g'),
        lower(email_gov),
        initcap(ceofname),
        initcap(ceolname),
        initcap(ceotitle),
        initcap(ceoaddr),
        initcap(ceocity),
        ceostate,
        ceozip,
        regexp_replace(ceophone, '[^0-9]', '', 'g'),
        ceoext,
        regexp_replace(ceofax, '[^0-9]', '', 'g'),
        lower(ceoemail),
        initcap(cfofname),
        initcap(cfolname),
        initcap(cfotitle),
        initcap(cfoaddr),
        initcap(cfocity),
        cfostate,
        cfozip,
        regexp_replace(cfophone, '[^0-9]', '', 'g'),
        cfoext,
        regexp_replace(cfofax, '[^0-9]', '', 'g'),
        lower(cfoemail),
        initcap(pafname),
        initcap(palname),
        initcap(patitle),
        initcap(paaddr),
        initcap(pacity),
        pastate,
        pazip,
        regexp_replace(paphone, '[^0-9]', '', 'g'),
        paext,
        regexp_replace(pafax, '[^0-9]', '', 'g'),
        lower(paemail),
        initcap(tiffname),
        initcap(tiflname),
        initcap(tiftitle),
        initcap(tifaddr),
        initcap(tifcity),
        tifstate,
        tifzip,
        regexp_replace(tifphone, '[^0-9]', '', 'g'),
        tifext,
        regexp_replace(tiffax, '[^0-9]', '', 'g'),
        lower(tifemail),
        initcap(foiafname),
        initcap(foialname),
        initcap(foiatitle),
        initcap(foiaaddr),
        initcap(foiacity),
        foiastate,
        foiazip,
        regexp_replace(foiaphone, '[^0-9]', '', 'g'),
        foiaext,
        regexp_replace(foiafax, '[^0-9]', '', 'g'),
        lower(foiaemail),
        concat(slugify(county), '/', slugify(unitname), '-', slugify(description))
    FROM raw.contacts
ON CONFLICT (code)
    DO UPDATE SET
        county = excluded.county,
        unitname = excluded.unitname,
        description = excluded.description,
        code = excluded.code,
        address = initcap(excluded.address),
        city = initcap(excluded.city),
        state = excluded.state,
        zip = excluded.zip,
        firstname = initcap(excluded.firstname),
        lastname = initcap(excluded.lastname),
        title = initcap(excluded.title),
        phone = regexp_replace(excluded.phone, '[^0-9]', '', 'g'),
        ext = excluded.ext,
        fax = regexp_replace(excluded.fax, '[^0-9]', '', 'g'),
        email_gov = lower(excluded.email_gov),
        ceofname = initcap(excluded.ceofname),
        ceolname = initcap(excluded.ceolname),
        ceotitle = initcap(excluded.ceotitle),
        ceoaddr = initcap(excluded.ceoaddr),
        ceocity = initcap(excluded.ceocity),
        ceostate = excluded.ceostate,
        ceozip = excluded.ceozip,
        ceophone = regexp_replace(excluded.ceophone, '[^0-9]', '', 'g'),
        ceoext = excluded.ceoext,
        ceofax = regexp_replace(excluded.ceofax, '[^0-9]', '', 'g'),
        ceoemail = lower(excluded.ceoemail),
        cfofname = initcap(excluded.cfofname),
        cfolname = initcap(excluded.cfolname),
        cfotitle = initcap(excluded.cfotitle),
        cfoaddr = initcap(excluded.cfoaddr),
        cfocity = initcap(excluded.cfocity),
        cfostate = excluded.cfostate,
        cfozip = excluded.cfozip,
        cfophone = regexp_replace(excluded.cfophone, '[^0-9]', '', 'g'),
        cfoext = excluded.cfoext,
        cfofax = regexp_replace(excluded.cfofax, '[^0-9]', '', 'g'),
        cfoemail = lower(excluded.cfoemail),
        pafname = initcap(excluded.pafname),
        palname = initcap(excluded.palname),
        patitle = initcap(excluded.patitle),
        paaddr = initcap(excluded.paaddr),
        pacity = initcap(excluded.pacity),
        pastate = excluded.pastate,
        pazip = excluded.pazip,
        paphone = regexp_replace(excluded.paphone, '[^0-9]', '', 'g'),
        paext = excluded.paext,
        pafax = regexp_replace(excluded.pafax, '[^0-9]', '', 'g'),
        paemail = lower(excluded.paemail),
        tiffname = initcap(excluded.tiffname),
        tiflname = initcap(excluded.tiflname),
        tiftitle  = initcap(excluded.tiftitle),
        tifaddr = initcap(excluded.tifaddr),
        tifcity = initcap(excluded.tifcity),
        tifstate = excluded.tifstate,
        tifzip = excluded.tifzip,
        tifphone = regexp_replace(excluded.tifphone, '[^0-9]', '', 'g'),
        tifext = excluded.tifext,
        tiffax = regexp_replace(excluded.tiffax, '[^0-9]', '', 'g'),
        tifemail = lower(excluded.tifemail),
        foiafname = initcap(excluded.foiafname),
        foialname = initcap(excluded.foialname),
        foiatitle = initcap(excluded.foiatitle),
        foiaaddr = initcap(excluded.foiaaddr),
        foiacity = initcap(excluded.foiacity),
        foiastate = excluded.foiastate,
        foiazip = excluded.foiazip,
        foiaphone = regexp_replace(excluded.foiaphone, '[^0-9]', '', 'g'),
        foiaext = excluded.foiaext,
        foiafax = regexp_replace(excluded.foiafax, '[^0-9]', '', 'g'),
        foiaemail = lower(excluded.foiaemail)
;